/**
 * Pre-seeded MSVC and General C++ Compiler Error Patterns
 */

import type { ErrorPattern } from '../types/index.js';

export const MSVC_PATTERNS: ErrorPattern[] = [
  // ============================================================================
  // MSVC Compiler Errors (C2xxx)
  // ============================================================================
  {
    id: 'msvc-c2065-undeclared',
    category: 'compiler',
    compiler: 'msvc',
    regex: "error C2065:\\s*'([^']+)'\\s*:\\s*undeclared identifier",
    extractors: { identifier: '$1' },
    description: 'Undeclared identifier - symbol not found',
    commonCauses: [
      'Missing #include for the header that declares the symbol',
      'Typo in variable/function name',
      'Symbol is in a different namespace',
      'Missing using directive or namespace qualification',
    ],
    fixes: [
      {
        id: 'add-include',
        description: 'Add missing #include directive',
        type: 'file_edit',
        steps: [
          'Search for header file that declares ${identifier}',
          'Add #include "header.h" or #include <header> at top of file',
        ],
        appliedCount: 0,
        successCount: 0,
      },
      {
        id: 'add-namespace',
        description: 'Add namespace qualification',
        type: 'file_edit',
        steps: [
          'Check which namespace ${identifier} belongs to',
          'Add namespace::${identifier} or using namespace directive',
        ],
        appliedCount: 0,
        successCount: 0,
      },
    ],
    occurrences: 0,
    lastSeen: '',
    successRate: 0,
  },
  {
    id: 'msvc-c2079-undefined-class',
    category: 'compiler',
    compiler: 'msvc',
    regex: "error C2079:\\s*'([^']+)'\\s*uses undefined (?:class|struct)\\s*'([^']+)'",
    extractors: { variable: '$1', type: '$2' },
    description: 'Using undefined class/struct (forward declaration not sufficient)',
    commonCauses: [
      'Only forward declaration exists, full definition needed',
      'Header with class definition not included',
      'Circular dependency issue',
    ],
    fixes: [
      {
        id: 'include-full-definition',
        description: 'Include header with full class definition',
        type: 'file_edit',
        steps: [
          'Find the header that fully defines ${type}',
          'Replace forward declaration with #include',
        ],
        appliedCount: 0,
        successCount: 0,
      },
      {
        id: 'use-pointer',
        description: 'Use pointer/reference instead of value type',
        type: 'file_edit',
        steps: [
          'Change ${type} ${variable} to ${type}* ${variable} or std::unique_ptr<${type}>',
          'This allows using forward declaration',
        ],
        appliedCount: 0,
        successCount: 0,
      },
    ],
    occurrences: 0,
    lastSeen: '',
    successRate: 0,
  },
  {
    id: 'msvc-c2143-syntax-missing',
    category: 'compiler',
    compiler: 'msvc',
    regex: "error C2143:\\s*syntax error\\s*:\\s*missing\\s*'([^']+)'",
    extractors: { token: '$1' },
    description: 'Syntax error - missing token',
    commonCauses: [
      'Missing semicolon at end of statement',
      'Missing closing brace, parenthesis, or bracket',
      'Missing comma in parameter list',
    ],
    fixes: [
      {
        id: 'add-missing-token',
        description: 'Add the missing token',
        type: 'file_edit',
        steps: [
          "Look at the line number in the error",
          "Check the previous line - often the missing '${token}' belongs there",
          'Add ${token} at the appropriate location',
        ],
        appliedCount: 0,
        successCount: 0,
      },
    ],
    occurrences: 0,
    lastSeen: '',
    successRate: 0,
  },
  {
    id: 'msvc-c2039-not-member',
    category: 'compiler',
    compiler: 'msvc',
    regex: "error C2039:\\s*'([^']+)'\\s*:\\s*is not a member of\\s*'([^']+)'",
    extractors: { member: '$1', type: '$2' },
    description: 'Member not found in class/struct',
    commonCauses: [
      'Typo in member name',
      'Member is private/protected',
      'Using wrong overload or template specialization',
      'Header version mismatch',
    ],
    fixes: [
      {
        id: 'check-member-name',
        description: 'Verify member name spelling',
        type: 'manual',
        steps: [
          'Open the header defining ${type}',
          'Find the correct member name (may be different case or spelling)',
          'Update the code to use correct member name',
        ],
        appliedCount: 0,
        successCount: 0,
      },
    ],
    occurrences: 0,
    lastSeen: '',
    successRate: 0,
  },
  {
    id: 'msvc-c2664-cannot-convert',
    category: 'compiler',
    compiler: 'msvc',
    regex: "error C2664:\\s*'([^']+)'\\s*:\\s*cannot convert argument (\\d+) from\\s*'([^']+)'\\s*to\\s*'([^']+)'",
    extractors: { function: '$1', argNum: '$2', fromType: '$3', toType: '$4' },
    description: 'Cannot convert argument type',
    commonCauses: [
      'Passing wrong type to function',
      'Missing const qualifier',
      'Implicit conversion not available',
      'Unicode/ANSI string mismatch',
    ],
    fixes: [
      {
        id: 'add-cast',
        description: 'Add explicit type conversion',
        type: 'file_edit',
        steps: [
          'For argument ${argNum}, convert from ${fromType} to ${toType}',
          'Use static_cast<${toType}>(arg) or appropriate conversion function',
        ],
        appliedCount: 0,
        successCount: 0,
      },
      {
        id: 'fix-const',
        description: 'Fix const-correctness',
        type: 'file_edit',
        steps: [
          'If ${toType} has const and ${fromType} does not, the variable may need to be const',
          'Or use const_cast<> if semantically correct',
        ],
        appliedCount: 0,
        successCount: 0,
      },
    ],
    occurrences: 0,
    lastSeen: '',
    successRate: 0,
  },
  {
    id: 'msvc-c2512-no-default-constructor',
    category: 'compiler',
    compiler: 'msvc',
    regex: "error C2512:\\s*'([^']+)'\\s*:\\s*no appropriate default constructor available",
    extractors: { type: '$1' },
    description: 'No default constructor available',
    commonCauses: [
      'Class has user-defined constructor but no default constructor',
      'Member requires initialization',
      'Base class has no default constructor',
    ],
    fixes: [
      {
        id: 'add-default-constructor',
        description: 'Add default constructor to class',
        type: 'file_edit',
        steps: [
          'Add ${type}() = default; to the class definition',
          'Or provide a constructor with default arguments',
        ],
        appliedCount: 0,
        successCount: 0,
      },
      {
        id: 'use-initializer',
        description: 'Use member initializer list',
        type: 'file_edit',
        steps: [
          'Initialize the member using constructor initializer list',
          'Example: MyClass() : member(value) {}',
        ],
        appliedCount: 0,
        successCount: 0,
      },
    ],
    occurrences: 0,
    lastSeen: '',
    successRate: 0,
  },
  {
    id: 'msvc-c2440-cannot-convert-init',
    category: 'compiler',
    compiler: 'msvc',
    regex: "error C2440:\\s*'([^']+)'\\s*:\\s*cannot convert from\\s*'([^']+)'\\s*to\\s*'([^']+)'",
    extractors: { context: '$1', fromType: '$2', toType: '$3' },
    description: 'Cannot convert types in initialization/assignment',
    commonCauses: [
      'Incompatible pointer types',
      'Narrowing conversion in initialization',
      'Missing conversion operator',
    ],
    fixes: [
      {
        id: 'explicit-conversion',
        description: 'Add explicit conversion',
        type: 'file_edit',
        steps: [
          'Use static_cast, dynamic_cast, or reinterpret_cast as appropriate',
          'Convert from ${fromType} to ${toType}',
        ],
        appliedCount: 0,
        successCount: 0,
      },
    ],
    occurrences: 0,
    lastSeen: '',
    successRate: 0,
  },
  {
    id: 'msvc-c2248-private-member',
    category: 'compiler',
    compiler: 'msvc',
    regex: "error C2248:\\s*'([^']+)'\\s*:\\s*cannot access (private|protected) member",
    extractors: { member: '$1', access: '$2' },
    description: 'Cannot access private/protected member',
    commonCauses: [
      'Trying to access private member from outside class',
      'Missing friend declaration',
      'Need to use public accessor method',
    ],
    fixes: [
      {
        id: 'use-accessor',
        description: 'Use public accessor method',
        type: 'file_edit',
        steps: [
          'Find or create a public getter/setter for ${member}',
          'Use the accessor instead of direct member access',
        ],
        appliedCount: 0,
        successCount: 0,
      },
      {
        id: 'add-friend',
        description: 'Add friend declaration',
        type: 'file_edit',
        steps: [
          'Add friend class/function declaration in the class definition',
          'This grants access to ${access} members',
        ],
        appliedCount: 0,
        successCount: 0,
      },
    ],
    occurrences: 0,
    lastSeen: '',
    successRate: 0,
  },
  {
    id: 'msvc-c2059-syntax-error',
    category: 'compiler',
    compiler: 'msvc',
    regex: "error C2059:\\s*syntax error\\s*:\\s*'([^']+)'",
    extractors: { token: '$1' },
    description: 'General syntax error',
    commonCauses: [
      'Unexpected token in code',
      'Macro expansion issue',
      'Missing preprocessor include guard causing redefinition',
    ],
    fixes: [
      {
        id: 'check-syntax',
        description: 'Check syntax around the error location',
        type: 'manual',
        steps: [
          "Look at the line with '${token}'",
          'Check for missing braces, semicolons, or operators',
          'Check if a macro is expanding incorrectly',
        ],
        appliedCount: 0,
        successCount: 0,
      },
    ],
    occurrences: 0,
    lastSeen: '',
    successRate: 0,
  },
  {
    id: 'msvc-c2061-syntax-identifier',
    category: 'compiler',
    compiler: 'msvc',
    regex: "error C2061:\\s*syntax error\\s*:\\s*identifier\\s*'([^']+)'",
    extractors: { identifier: '$1' },
    description: 'Syntax error with identifier',
    commonCauses: [
      'Missing type declaration or forward declaration',
      'Typo in type name',
      'Missing #include for type definition',
    ],
    fixes: [
      {
        id: 'add-forward-declaration',
        description: 'Add forward declaration',
        type: 'file_edit',
        steps: [
          'Add class ${identifier}; or struct ${identifier}; before use',
          'Or include the header that defines ${identifier}',
        ],
        appliedCount: 0,
        successCount: 0,
      },
    ],
    occurrences: 0,
    lastSeen: '',
    successRate: 0,
  },

  // ============================================================================
  // MSVC Linker Errors (LNKxxxx)
  // ============================================================================
  {
    id: 'msvc-lnk2019-unresolved',
    category: 'linker',
    compiler: 'msvc',
    regex: 'error LNK2019:\\s*unresolved external symbol\\s*"?([^"]+)"?\\s*referenced in function\\s*"?([^"]+)"?',
    extractors: { symbol: '$1', function: '$2' },
    description: 'Unresolved external symbol - linker cannot find symbol definition',
    commonCauses: [
      'Source file containing definition not compiled/linked',
      'Library not linked',
      'Function declared but not defined',
      'Name mangling mismatch (extern "C" missing)',
      'Static library not linked',
    ],
    fixes: [
      {
        id: 'add-source-to-target',
        description: 'Add source file to CMake target',
        type: 'cmake_change',
        steps: [
          'Find the .cpp file that defines ${symbol}',
          'Add it to the target_sources() or add_library()/add_executable() in CMakeLists.txt',
        ],
        appliedCount: 0,
        successCount: 0,
      },
      {
        id: 'link-library',
        description: 'Link required library',
        type: 'cmake_change',
        steps: [
          'Find which library provides ${symbol}',
          'Add target_link_libraries(your_target PRIVATE library_name)',
        ],
        appliedCount: 0,
        successCount: 0,
      },
      {
        id: 'implement-function',
        description: 'Implement the missing function',
        type: 'file_edit',
        steps: [
          'The function ${symbol} is declared but not defined',
          'Add the implementation in an appropriate .cpp file',
        ],
        appliedCount: 0,
        successCount: 0,
      },
    ],
    occurrences: 0,
    lastSeen: '',
    successRate: 0,
  },
  {
    id: 'msvc-lnk2001-unresolved',
    category: 'linker',
    compiler: 'msvc',
    regex: 'error LNK2001:\\s*unresolved external symbol\\s*"?([^"]+)"?',
    extractors: { symbol: '$1' },
    description: 'Unresolved external symbol (static member or vtable)',
    commonCauses: [
      'Static class member declared but not defined',
      'Pure virtual function not implemented in derived class',
      'Virtual destructor not defined',
      'Missing library dependency',
    ],
    fixes: [
      {
        id: 'define-static-member',
        description: 'Define static member variable',
        type: 'file_edit',
        steps: [
          'Add definition: Type ClassName::memberName; in a .cpp file',
          'Or for inline static in C++17: inline static Type memberName{};',
        ],
        appliedCount: 0,
        successCount: 0,
      },
      {
        id: 'implement-virtual',
        description: 'Implement virtual function',
        type: 'file_edit',
        steps: [
          'Check if ${symbol} is a virtual function',
          'Implement the function in the derived class',
        ],
        appliedCount: 0,
        successCount: 0,
      },
    ],
    occurrences: 0,
    lastSeen: '',
    successRate: 0,
  },
  {
    id: 'msvc-lnk1120-unresolved-count',
    category: 'linker',
    compiler: 'msvc',
    regex: 'error LNK1120:\\s*(\\d+)\\s*unresolved externals?',
    extractors: { count: '$1' },
    description: 'Multiple unresolved external symbols',
    commonCauses: [
      'Multiple missing definitions',
      'Library not linked',
      'Object files not included in link',
    ],
    fixes: [
      {
        id: 'resolve-all',
        description: 'Resolve individual LNK2019/LNK2001 errors above',
        type: 'manual',
        steps: [
          'Look at the LNK2019 or LNK2001 errors above this one',
          'Each one tells you which symbol is missing',
          'Fix them individually - this error will disappear',
        ],
        appliedCount: 0,
        successCount: 0,
      },
    ],
    occurrences: 0,
    lastSeen: '',
    successRate: 0,
  },
  {
    id: 'msvc-lnk1104-cannot-open',
    category: 'linker',
    compiler: 'msvc',
    regex: "error LNK1104:\\s*cannot open file\\s*'([^']+)'",
    extractors: { file: '$1' },
    description: 'Cannot open file during linking',
    commonCauses: [
      'Library file does not exist',
      'Library path not in linker search path',
      'File is locked by another process',
      'Antivirus blocking access',
    ],
    fixes: [
      {
        id: 'add-library-path',
        description: 'Add library directory to search path',
        type: 'cmake_change',
        steps: [
          'Use target_link_directories() or link_directories() in CMakeLists.txt',
          'Or use full path to ${file} in target_link_libraries()',
        ],
        appliedCount: 0,
        successCount: 0,
      },
      {
        id: 'install-library',
        description: 'Install missing library',
        type: 'dependency',
        steps: [
          'Install the library that provides ${file}',
          'For vcpkg: vcpkg install <package>',
          'Ensure vcpkg toolchain file is used',
        ],
        appliedCount: 0,
        successCount: 0,
      },
    ],
    occurrences: 0,
    lastSeen: '',
    successRate: 0,
  },
  {
    id: 'msvc-lnk2005-already-defined',
    category: 'linker',
    compiler: 'msvc',
    regex: 'error LNK2005:\\s*"?([^"]+)"?\\s*already defined in\\s*([^\\s]+)',
    extractors: { symbol: '$1', object: '$2' },
    description: 'Symbol already defined in another object file',
    commonCauses: [
      'Function defined in header without inline',
      'Global variable defined in header',
      'Same source file compiled twice',
      'Static library linked multiple times',
    ],
    fixes: [
      {
        id: 'make-inline',
        description: 'Make function inline',
        type: 'file_edit',
        steps: [
          'If ${symbol} is a function defined in a header, add inline keyword',
          'Or move definition to a .cpp file',
        ],
        appliedCount: 0,
        successCount: 0,
      },
      {
        id: 'extern-variable',
        description: 'Use extern for global variable',
        type: 'file_edit',
        steps: [
          'In header: extern Type varName;',
          'In one .cpp: Type varName = value;',
        ],
        appliedCount: 0,
        successCount: 0,
      },
    ],
    occurrences: 0,
    lastSeen: '',
    successRate: 0,
  },
  {
    id: 'msvc-lnk1169-multiple-symbols',
    category: 'linker',
    compiler: 'msvc',
    regex: 'error LNK1169:\\s*one or more multiply defined symbols found',
    description: 'Multiple symbol definition errors',
    commonCauses: [
      'Multiple LNK2005 errors above',
      'Same symbol defined in multiple translation units',
    ],
    fixes: [
      {
        id: 'fix-lnk2005',
        description: 'Fix the LNK2005 errors above',
        type: 'manual',
        steps: [
          'Look at the LNK2005 errors above this one',
          'Each one tells you which symbol is multiply defined',
          'Make functions inline or use extern for variables',
        ],
        appliedCount: 0,
        successCount: 0,
      },
    ],
    occurrences: 0,
    lastSeen: '',
    successRate: 0,
  },

  // ============================================================================
  // MSVC Warnings treated as errors
  // ============================================================================
  {
    id: 'msvc-c4996-deprecated',
    category: 'compiler',
    compiler: 'msvc',
    regex: "(?:error|warning) C4996:\\s*'([^']+)'.*(?:deprecated|was declared deprecated)",
    extractors: { function: '$1' },
    description: 'Deprecated function/feature used',
    commonCauses: [
      'Using deprecated C runtime functions',
      'Using deprecated STL features',
      'Using functions marked [[deprecated]]',
    ],
    fixes: [
      {
        id: 'use-safe-version',
        description: 'Use the safe/modern version',
        type: 'file_edit',
        steps: [
          'Replace ${function} with its _s (safe) version if available',
          'Or use modern C++ equivalent (e.g., std::string instead of strcpy)',
        ],
        appliedCount: 0,
        successCount: 0,
      },
      {
        id: 'disable-warning',
        description: 'Disable deprecation warning (not recommended)',
        type: 'cmake_change',
        steps: [
          'Add _CRT_SECURE_NO_WARNINGS to preprocessor definitions',
          'Or use #pragma warning(disable: 4996) locally',
        ],
        appliedCount: 0,
        successCount: 0,
      },
    ],
    occurrences: 0,
    lastSeen: '',
    successRate: 0,
  },
];
